backend:
  name: git-gateway
  branch: main

# When testing locally with the netlify-cms-proxy-server
local_backend: true

# Media folder where uploaded images will be saved in the repo
media_folder: static/images
# Public folder where the images will be accessed in the built site
public_folder: /images

# Enable editorial workflow (drafts, review, publish)
publish_mode: editorial_workflow

# Define collections
collections:
  # Events
  - name: "events"
    label: "Events"
    folder: "_events"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "End Date", name: "end_date", widget: "datetime", required: false }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Category", name: "category", widget: "select", options: ["Event", "Announcement"] }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }

  # Regular Events
  - name: "regular_events"
    label: "Regular Events"
    folder: "_data"
    file: "regular_events.yml"
    fields:
      - label: "Regular Events"
        name: "events"
        widget: "list"
        summary: "{{fields.title}} - {{fields.frequency}} on {{fields.day}} at {{fields.time}}"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Frequency"
            name: "frequency"
            widget: "select"
            options: ["Weekly", "Monthly"]
          - label: "Day"
            name: "day"
            widget: "select"
            options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
          - label: "Time"
            name: "time"
            widget: "string"
          - label: "Location"
            name: "location"
            widget: "string"
            default: "Islamic Society of Sheboygan"
          - label: "Notes"
            name: "notes"
            widget: "text"
            required: false
          - label: "Active"
            name: "active"
            widget: "boolean"
            default: true

  # Announcements
  - name: "announcements"
    label: "Announcements"
    folder: "_data"
    file: "announcements.yml"
    fields:
      - label: "Active Announcements"
        name: "active"
        widget: "list"
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}
          - {label: "Start Date", name: "start_date", widget: "datetime", required: false}
          - {label: "End Date", name: "end_date", widget: "datetime", required: false}
          - {label: "Priority", name: "priority", widget: "select", options: ["High", "Medium", "Low"], default: "Medium"}
          - {label: "Link Text", name: "link_text", widget: "string", required: false}
          - {label: "Link URL", name: "link_url", widget: "string", required: false}

  # Settings and configuration
  - name: "settings"
    label: "Settings"
    files:
      - name: "prayer_times"
        label: "Prayer Times"
        file: "prayer_times.yml"
        fields:
          - label: "Prayer Times Settings"
            name: "settings"
            widget: "object"
            fields:
              - label: "Calculation Method"
                name: "method"
                widget: "select"
                options: ["ISNA", "MWL", "Egyptian", "Karachi", "Makkah"]
              - label: "Asr Calculation Method"
                name: "asr_method"
                widget: "select"
                options: ["Standard", "Hanafi"]
              - label: "DST"
                name: "dst"
                widget: "boolean"
                default: true
          - label: "Time Adjustments (minutes)"
            name: "adjustments"
            widget: "object"
            fields:
              - label: "Fajr"
                name: "fajr"
                widget: "number"
                default: 0
              - label: "Sunrise"
                name: "sunrise"
                widget: "number"
                default: 0
              - label: "Dhuhr"
                name: "dhuhr"
                widget: "number"
                default: 0
              - label: "Asr"
                name: "asr"
                widget: "number"
                default: 0
              - label: "Maghrib"
                name: "maghrib"
                widget: "number"
                default: 0
              - label: "Isha"
                name: "isha"
                widget: "number"
                default: 0
          - label: "Jumu'ah Times"
            name: "jumua_times"
            widget: "list"
            required: false
            fields:
              - label: "Time"
                name: "time"
                widget: "string"
                pattern: ["^([1-9]|1[0-2]):[0-5][0-9]\\s*[AaPp][Mm]$", "Please enter a valid time in 12-hour format (e.g., 2:00 PM)"]
              - label: "Location"
                name: "location"
                widget: "string"
                required: false
              - label: "Notes"
                name: "notes"
                widget: "string"
                required: false

      - name: "leadership"
        label: "Leadership Team"
        file: "leadership.yml"
        fields:
          - label: "Team Members"
            name: "team"
            widget: "list"
            summary: "{{fields.name}}, {{fields.position}}"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Position"
                name: "position"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
                required: false
              - label: "Bio"
                name: "bio"
                widget: "text"
                required: false
