backend:
  name: git-gateway
  branch: main

collections:
  - name: "events"
    label: "Events"
    folder: "_events"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Event Type", name: "type", widget: "select", options: ["one-time", "recurring"], default: "one-time"}
      - {label: "Date", name: "date", widget: "datetime", required: false, hint: "Required for one-time events"}
      - {label: "Day of Week", name: "day", widget: "select", options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], required: false, hint: "Required for recurring events"}
      - {label: "Time", name: "time", widget: "string", required: true}
      - {label: "Location", name: "location", widget: "string", required: true, default: "Islamic Society of Sheboygan"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "announcements"
    label: "Announcements"
    folder: "_announcements"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "announcement"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Content", name: "body", widget: "markdown", required: true}

  - name: "leadership"
    label: "Leadership"
    folder: "_leadership"
    create: true
    summary: "{{title}} - {{position}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "leadership"}
      - {label: "Name", name: "title", widget: "string", required: true}
      - {label: "Position", name: "position", widget: "string", required: true}
      - {label: "Order", name: "order", widget: "number", default: 0}
      - {label: "Image", name: "image", widget: "image", required: false} 