backend:
  name: git-gateway
  branch: main # Branch to update

# When testing locally with the netlify-cms-proxy-server
local_backend: false

# Media folder where uploaded images will be saved in the repo
media_folder: "assets/images/uploads"
# Public folder where the images will be accessed in the built site
public_folder: "/assets/images/uploads"

# Enable editorial workflow (drafts, review, publish)
publish_mode: editorial_workflow

# Define collections
collections:
  # Events
  - name: "events"
    label: "Events"
    folder: "_events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "events/{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start Date & Time", name: "start_date", widget: "datetime"}
      - {label: "End Date & Time", name: "end_date", widget: "datetime", required: false}
      - {label: "Location", name: "location", widget: "string", default: "Islamic Society of Sheboygan"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Organizer", name: "organizer", widget: "string", required: false}
      - {label: "Contact Email", name: "contact_email", widget: "string", required: false}
      - {label: "Contact Phone", name: "contact_phone", widget: "string", required: false}
      - {label: "Registration URL", name: "registration_url", widget: "string", required: false}
      - {label: "Registration Email", name: "registration_email", widget: "string", required: false}
      - {label: "Is Recurring Event?", name: "recurring", widget: "boolean", default: false}
      - {label: "Recurrence Pattern", name: "recurrence", widget: "select", options: ["Daily", "Weekly", "Monthly"], required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # Settings and configuration
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      # Prayer Times
      - name: "prayer-times"
        label: "Prayer Times"
        file: "_data/prayer_times.yml"
        description: "Configure prayer times calculation settings and Jumu'ah prayer time"
        fields:
          - label: "Calculation Settings"
            name: "settings"
            widget: "object"
            collapsed: false
            fields:
              - {label: "Calculation Method", name: "method", widget: "select", options: ["ISNA", "MWL", "Egyptian", "Karachi", "Makkah"], default: "ISNA", hint: "Select the calculation method for prayer times"}
              - {label: "Juristic Method (Asr)", name: "asr_method", widget: "select", options: ["Standard", "Hanafi"], default: "Standard", hint: "Select the juristic method for Asr prayer time"}
              - {label: "Daylight Saving Time", name: "dst", widget: "boolean", default: true, hint: "Enable if your location observes daylight saving time"}

          - label: "Time Adjustments"
            name: "adjustments"
            widget: "object"
            collapsed: false
            description: "Use these adjustments to set iqamah times. For example, if Fajr athan is at 5:30 AM and you want iqamah at 5:45 AM, set Fajr to +15 minutes."
            fields:
              - {label: "Fajr (minutes)", name: "fajr", widget: "number", default: 0, hint: "Add minutes to athan time for iqamah (e.g., +15 for 15 minutes after athan)"}
              - {label: "Sunrise (minutes)", name: "sunrise", widget: "number", default: 0, hint: "Add minutes to athan time for iqamah (e.g., +15 for 15 minutes after athan)"}
              - {label: "Dhuhr (minutes)", name: "dhuhr", widget: "number", default: 0, hint: "Add minutes to athan time for iqamah (e.g., +15 for 15 minutes after athan)"}
              - {label: "Asr (minutes)", name: "asr", widget: "number", default: 0, hint: "Add minutes to athan time for iqamah (e.g., +15 for 15 minutes after athan)"}
              - {label: "Maghrib (minutes)", name: "maghrib", widget: "number", default: 0, hint: "Add minutes to athan time for iqamah (e.g., +15 for 15 minutes after athan)"}
              - {label: "Isha (minutes)", name: "isha", widget: "number", default: 0, hint: "Add minutes to athan time for iqamah (e.g., +15 for 15 minutes after athan)"}

          - label: "Jumu'ah Prayer"
            name: "jumuah"
            widget: "object"
            collapsed: false
            fields:
              - {label: "Jumu'ah Time", name: "time", widget: "string", default: "1:10 PM", hint: "Enter the time for Friday prayer (Jumu'ah) in 12-hour format (e.g., 1:10 PM)"}
              - {label: "Additional Notes", name: "note", widget: "string", required: false, hint: "Add any additional notes about Jumu'ah prayer"}

      # Team/Leadership
      - name: "team"
        label: "Leadership Team"
        file: "_data/team_members.yml"
        description: "Edit the mosque leadership team members. Each line should be in the format: Name, Position"
        fields:
          - label: "Team Members"
            name: "members"
            widget: "list"
            label_singular: "Team Member"
            summary: "{{fields.name}}, {{fields.position}}"
            fields:
              - {label: "Full Name", name: "name", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}

      # Navigation
      - name: "navigation"
        label: "Navigation Menu"
        file: "_data/navigation.yml"
        description: "Site navigation configuration"
        fields:
          - label: "Main Menu Items"
            name: "main"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}

      # Regular Events
      - name: "regular_events"
        label: "Regular Events"
        file: "_data/regular_events.yml"
        description: "Manage regular weekly/monthly events"
        fields:
          - label: "Regular Events"
            name: "events"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - {label: "Day", name: "day", widget: "select", options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]}
              - {label: "Time", name: "time", widget: "string"}
              - {label: "Location", name: "location", widget: "string", default: "Islamic Society of Sheboygan"}
              - {label: "Notes", name: "notes", widget: "string", required: false}

      # Homepage configuration
      - name: "homepage"
        label: "Homepage Settings"
        file: "_data/homepage.yml"
        description: "Homepage content configuration"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "string"}
          - {label: "Hero Image", name: "hero_image", widget: "image", required: false}
          - label: "Featured Announcements"
            name: "featured_announcements"
            widget: "list"
            required: false
            max: 3
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Content", name: "content", widget: "markdown"}
              - {label: "Link Text", name: "link_text", widget: "string", default: "Read More"}
              - {label: "Link URL", name: "link_url", widget: "string"}

      # Announcements
      - name: "announcements"
        label: "Announcements"
        file: "_data/announcements.yml"
        description: "Manage site announcements"
        fields:
          - label: "Active Announcements"
            name: "active"
            widget: "list"
            required: false
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Content", name: "content", widget: "markdown"}
              - {label: "Start Date", name: "start_date", widget: "datetime", required: false}
              - {label: "End Date", name: "end_date", widget: "datetime", required: false}
              - {label: "Priority", name: "priority", widget: "select", options: ["High", "Medium", "Low"], default: "Medium"}
              - {label: "Link Text", name: "link_text", widget: "string", required: false}
              - {label: "Link URL", name: "link_url", widget: "string", required: false}
